Repository SolutionGuidance/psm, pull requests merged in 2018-04, with the labels that each got.

#742 Fix "No file selected" on upload file prompt
  psm-app/cms-web/WebContent/WEB-INF/tags/attachment.tag
  psm-app/cms-web/WebContent/css/style.css
  psm-app/frontend/src/main/js/common.js
  psm-app/frontend/src/main/js/script.js
Labels: review

#732 Use jQuery "Mask" plugin instead of "Masked Input" plugin
  psm-app/build.gradle
  psm-app/cms-business-process/src/main/resources/cms.validation.drl
  psm-app/cms-web/WebContent/templates/includes/html_head.template.html
  psm-app/frontend/package-lock.json
  psm-app/frontend/package.json
  psm-app/frontend/src/main/js/admin/script.js
  psm-app/frontend/src/main/js/common.js
  psm-app/frontend/src/main/js/script.js
  psm-app/frontend/src/vendor/js/jquery.maskedinput.min.js
  psm-app/integration-tests/src/test/java/gov/medicaid/features/PsmPage.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/enrollment/steps/EnrollmentSteps.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/enrollment/steps/ValidationStepDefinitions.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/enrollment/ui/IndividualInfoPage.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/enrollment/ui/OrganizationInfoPage.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/enrollment/ui/OwnershipInfoPage.java
  psm-app/integration-tests/src/test/resources/features/enrollment/validation.feature
Labels: review

#744 Add Checkstyle rules for space separators
  psm-app/checkstyle.xml
  psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/Exclusion.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/OnboardingServiceBean.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/RegistrationServiceBean.java
  psm-app/cms-web/src/main/java/gov/medicaid/security/CustomAuthenticationProcessingFilter.java
  psm-app/cms-web/src/main/java/gov/medicaid/security/DefaultExternalAuthenticationProvider.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/enrollment/steps/EnrollmentStepDefinitions.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/general/steps/ChangePasswordStepDefinitions.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/general/steps/GeneralSteps.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/general/steps/LoginStepDefinitions.java
  psm-app/integration-tests/src/test/java/gov/medicaid/features/general/steps/LogoutStepDefinitions.java
  psm-app/services/src/main/java/gov/medicaid/binders/FacilityContractsFormBinder.java
  psm-app/services/src/main/java/gov/medicaid/binders/OrganizationInfoFormBinder.java
  psm-app/services/src/main/java/gov/medicaid/binders/OwnershipInfoFormBinder.java
  psm-app/services/src/main/java/gov/medicaid/binders/ProviderSetupFormBinder.java
  psm-app/services/src/main/java/gov/medicaid/entities/AgreementDocument.java
  psm-app/services/src/main/java/gov/medicaid/entities/OwnershipInformation.java
  psm-app/services/src/main/java/gov/medicaid/entities/PersonBeneficialOwner.java
  psm-app/services/src/main/java/gov/medicaid/services/RegistrationService.java
Labels: review

#747 Add user help links for "Title V" etc. form labels
  psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/individual_disclosure.jsp
  psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/organization_disclosure.jsp
  psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/ownership_information.jsp
  psm-app/frontend/src/main/js/script.js
  psm-app/userhelp/source/enrollment.rst
Labels: review

#745 Improve integration test invocation
  psm-app/build.gradle
  psm-app/integration-tests/README.md
  psm-app/integration-tests/serenity.properties.template
Labels: review

#748 Refactor html head template to remove repeated mask plugin
  psm-app/cms-web/WebContent/templates/includes/html_head.template.html
Labels: review

#756 Remove outdated WebSphere-related documentation
  docs/Data Sync Implementation Notes.docx
  docs/Internal Database Authentication And External LDAP Authentication Implementation Notes.doc
  docs/Websphere Deployment Guide.doc
  docs/Websphere Notes.txt
  docs/deployment.txt
  docs/guvnor-was8-patch/WEB-INF/components.xml
  docs/guvnor-was8-patch/WEB-INF/web.xml
Labels: review

#737 341 notification storage
  psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/NotificationServiceBean.java
  psm-app/cms-business-process/src/main/resources/META-INF/persistence.xml
  psm-app/db/seed.sql
  psm-app/services/src/main/java/gov/medicaid/entities/SentNotification.java
Labels: migration, review

#763 Remove test SQL files
  psm-app/cms-web/src/main/resources/web-clear-data.sql
  psm-app/cms-web/src/main/resources/web-test-data.sql
Labels: review

#760 Remove extra colons from Personal Care Assistant pages
  psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/ind_agency_information.jsp
  psm-app/cms-web/WebContent/WEB-INF/pages/provider/enrollment/steps/pageTemplates/default/ind_pca_information.jsp
  psm-app/cms-web/WebContent/WEB-INF/pages/provider/profile/password.jsp
Labels: review

#764 Remove PECOS verification
  psm-app/cms-business-model/src/main/resources/EnrollmentServiceAPI.xsd
  psm-app/cms-business-model/src/main/resources/Entities.xsd
  psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/VerifyPECOSRecordHandler.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/verification/PECOSSearchClient.java
  psm-app/cms-business-process/src/main/resources/cms.screening.drl
  psm-app/cms-web/WebContent/WEB-INF/pages/admin/service_agent_review_screening.jsp
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/EnrollmentController.java
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/dto/ApprovalDTO.java
  psm-app/db/seed.sql
  psm-app/services/src/main/java/gov/medicaid/entities/Entity.java
  psm-app/services/src/main/java/gov/medicaid/services/util/XMLAdapter.java
  psm-app/services/src/main/resources/xslt/pecos_req.xsl
  psm-app/services/src/main/resources/xslt/pecos_res.xsl
  psm-app/userhelp/source/service-admin-help.rst
Labels: migration, review

#768 Add task queueing to RTM
  requirements/RTM.xlsx
Labels: review

#772 Add migration checklist to CONTRIB
  CONTRIBUTING.md
Labels: review

#769 Remove legacy SAM exclusion list verification
  psm-app/cms-business-model/src/main/resources/EnrollmentServiceAPI.xsd
  psm-app/cms-business-model/src/main/resources/Entities.xsd
  psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/SAMExcludedProvidersScreeningHandler.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/BusinessProcessServiceBean.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/verification/SAMExclusionSearchClient.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/verification/SAMExclusionServiceMatcher.java
  psm-app/cms-business-process/src/main/resources/EnrollmentProcess.bpmn
  psm-app/cms-web/WebContent/WEB-INF/pages/admin/service_agent_review_screening.jsp
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/EnrollmentController.java
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/dto/ApprovalDTO.java
  psm-app/services/src/main/resources/xslt/sam_search_req.xsl
  psm-app/services/src/main/resources/xslt/sam_search_res.xsl
  psm-app/services/src/main/resources/xslt/sam_verify_req.xsl
  psm-app/services/src/main/resources/xslt/sam_verify_res.xsl
  psm-app/userhelp/source/service-admin-help.rst
Labels: up-next

#741 Refactor npm-installed JS deps in gradle
  psm-app/build.gradle
Labels: review

#750 Add reject notifications
  psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/ProviderEnrollmentServiceBean.java
Labels: review

#780 Fix JavaScript style guide violations
  psm-app/frontend/src/main/js/common.js
Labels: review

#777 Remove documentation on external sources
  docs/DESIGN.md
Labels: review

#776 Remove legacy NPI lookup verification
  psm-app/cms-business-model/src/main/resources/EnrollmentServiceAPI.xsd
  psm-app/cms-business-model/src/main/resources/Entities.xsd
  psm-app/cms-business-process/src/main/java/gov/medicaid/process/enrollment/NPILookupHandler.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/services/impl/BusinessProcessServiceBean.java
  psm-app/cms-business-process/src/main/java/gov/medicaid/verification/NPILookupClient.java
  psm-app/cms-business-process/src/main/resources/EnrollmentProcess.bpmn
  psm-app/cms-web/WebContent/WEB-INF/pages/admin/service_agent_review_screening.jsp
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/EnrollmentController.java
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/dto/ApprovalDTO.java
  psm-app/db/seed.sql
  psm-app/services/src/main/java/gov/medicaid/entities/Entity.java
  psm-app/services/src/main/java/gov/medicaid/services/util/XMLAdapter.java
  psm-app/services/src/main/resources/xslt/npi_lookup_req.xsl
  psm-app/services/src/main/resources/xslt/npi_lookup_res.xsl
  psm-app/userhelp/source/service-admin-help.rst
Labels: review

#790 Add D3.js as a front end dependency
  psm-app/build.gradle
  psm-app/cms-web/WebContent/WEB-INF/mvc-dispatcher-servlet.xml
  psm-app/cms-web/WebContent/WEB-INF/pages/admin/report_page.jsp
  psm-app/cms-web/WebContent/templates/includes/html_head.template.html
  psm-app/cms-web/WebContent/templates/includes/nav.template.html
  psm-app/cms-web/src/main/java/gov/medicaid/controllers/admin/ReportController.java
  psm-app/frontend/package-lock.json
  psm-app/frontend/package.json
Labels: review

#795 Make the RTM parseable and map it to issues
  requirements/.gitignore
  requirements/README.md
  requirements/csv-exports/columns.txt
  requirements/csv-exports/reqs-ad.csv
  requirements/csv-exports/reqs-fr.csv
  requirements/csv-exports/reqs-ia.csv
  requirements/csv-exports/reqs-ii.csv
  requirements/csv-exports/reqs-iu.csv
  requirements/csv-exports/reqs-ph.csv
  requirements/csv-exports/reqs-sc.csv
  requirements/csv-exports/reqs-sq.csv
  requirements/notes-on-potential-new-reqs.txt
  requirements/psm-reqs.el
  requirements/psm_reqs.py
  requirements/reqs2any
  requirements/show-reqs
Labels: review
